module.exports = {
  preset: "ts-jest/presets/default",
  testEnvironment: "node",
  // transform: {},
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  transform: {
    '^.+\\.[tj]sx?$': [
      'ts-jest',
    ],
  },
  "transformIgnorePatterns": ["/node_modules/", '/__tests__/__mocks__/openai.ts'],
  testPathIgnorePatterns: [
    "/node_modules/",
    "/__mocks__/",
    "/__utils__/",
    "/__data__/",
    "/build/",
    "/dist/",
    // "/unit/parser/",
    // "/unit/prompt/",
    // // "/unit/llm/",
    // "/unit/utils/",
    // "/unit/utils/asyncCallWithTimeout.js",
    // "/unit/executor/",
    // "/unit/executor/core.js",
    // "/unit/executor/functions.js",
    // "/unit/executor/_metadata.js",
    // "/unit/executor/llm.js",
    // "/unit/callable/",
  ],
  collectCoverageFrom: [
    "<rootDir>/src/**/*.ts",
    "!<rootDir>/types/*.ts",
    "!<rootDir>/types/*.d.ts",
    "!<rootDir>/src/types/*.ts",
    "!<rootDir>/src/index.ts",
    "!<rootDir>/src/vector/*.ts",
    "!<rootDir>/src/embedding/*.ts",
    "!<rootDir>/src/interfaces/*.ts",
    "!<rootDir>/src/interfaces/*.ts",
    "!<rootDir>/types/*",
    "!<rootDir>/src/utils/modules/handlebars/helpers/*.ts",
  ],
};
