#!/usr/bin/env bash
#
# Generator for AUTOMATION.md - the live workflow vitals dashboard.
#
# Inputs (queried at runtime, no arguments):
#   - .github/workflows/*.yml          list of workflows
#   - scripts/agents/logs/*/           agent activity from committed run logs
#   - GitHub API via gh                workflow runs, PRs, issues, releases
#
# Outputs:
#   - AUTOMATION.md at the repo root (overwritten each invocation)
#
# Usage:
#   bash .github/vitals/generate.sh [output_path]
#
# Environment:
#   GH_TOKEN must be set (the calling workflow exports it from the bot token).
#
# Design notes:
#   - Status badges use shields.io URLs so the rendered file stays current
#     between vitals runs without re-fetching from the GitHub API.
#   - Live facts (counts, last release, stale PR list) are inlined as text
#     captured at generation time and labeled with the refresh timestamp.
#   - Every gh call is wrapped with `|| echo "<fallback>"` so transient
#     rate-limit or network errors degrade gracefully instead of crashing.

set -euo pipefail

OUTPUT="${1:-AUTOMATION.md}"
REPO=$(gh repo view --json nameWithOwner -q '.nameWithOwner' 2>/dev/null || echo "owner/repo")

# md_escape sanitizes a string for safe insertion into markdown table cells,
# link text, or bullet lines. It backslash-escapes characters that have
# markdown meaning (pipe, brackets, backtick, backslash) and collapses any
# newlines into spaces.
#
# Why this exists: bot PR titles and release names ultimately derive from
# agent output, which reads user-controlled issue and comment content. An
# adversarial title containing "]" or "|" could otherwise break the dashboard
# layout or smuggle an unexpected markdown link into AUTOMATION.md.
md_escape() {
  printf '%s' "$1" \
    | sed -e 's/\\/\\\\/g' \
          -e 's/`/\\`/g' \
          -e 's/|/\\|/g' \
          -e 's/\[/\\[/g' \
          -e 's/\]/\\]/g' \
    | tr '\n\r' '  '
}
NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)
SEVEN_DAYS_AGO=$(date -u -d '7 days ago' +%Y-%m-%dT%H:%M:%SZ)
SEVENTYTWO_HOURS_AGO=$(date -u -d '72 hours ago' +%Y-%m-%dT%H:%M:%SZ)

# --- Data gathering (resilient: any gh failure falls back to a neutral value) ---

STALE_PRS=$(gh pr list --repo "$REPO" --state open --author "app/llm-exe-bot" \
  --json number,title,createdAt,url --limit 200 2>/dev/null \
  | jq --arg cutoff "$SEVENTYTWO_HOURS_AGO" '[.[] | select(.createdAt < $cutoff)]' \
  2>/dev/null || echo "[]")
STALE_PR_COUNT=$(echo "$STALE_PRS" | jq 'length' 2>/dev/null || echo 0)

OPEN_BOT_PRS=$(gh pr list --repo "$REPO" --state open --author "app/llm-exe-bot" \
  --json number --limit 200 2>/dev/null | jq 'length' 2>/dev/null || echo 0)

OPEN_ISSUES=$(gh issue list --repo "$REPO" --state open --json number --limit 200 \
  2>/dev/null | jq 'length' 2>/dev/null || echo 0)

NEEDS_DISCUSSION=$(gh issue list --repo "$REPO" --state open --label needs-discussion \
  --json number --limit 200 2>/dev/null | jq 'length' 2>/dev/null || echo 0)

BREAKING_ISSUES=$(gh issue list --repo "$REPO" --state open --label breaking \
  --json number --limit 200 2>/dev/null | jq 'length' 2>/dev/null || echo 0)

LAST_RELEASE=$(gh release list --repo "$REPO" --limit 1 \
  --json tagName,publishedAt,name,url 2>/dev/null \
  | jq -c '.[0] // null' 2>/dev/null || echo "null")
RELEASE_TAG=$(echo "$LAST_RELEASE" | jq -r '.tagName // "none"')
RELEASE_DATE=$(echo "$LAST_RELEASE" | jq -r '.publishedAt // "never"')
RELEASE_URL=$(echo "$LAST_RELEASE" | jq -r '.url // ""')

DEV_DRAFT=$(gh pr list --repo "$REPO" --base main --head development \
  --state open --json number,title,isDraft,createdAt,url --limit 5 2>/dev/null \
  | jq -c '.[0] // null' 2>/dev/null || echo "null")

# --- Write the file ---

NOW_SHORT=$(date -u +%Y-%m-%d)
NOW_HUMAN=$(date -u +'%Y-%m-%d at %H:%M UTC')
NOW_BADGE=$(echo "$NOW_HUMAN" | sed 's/ /%20/g')
WORKFLOW_COUNT=$(ls -1 .github/workflows/*.yml 2>/dev/null | wc -l | tr -d ' ')

cat > "$OUTPUT" <<EOF
<div align="center">

# Automation Vitals

**Live state of the llm-exe automation system**

![workflows](https://img.shields.io/badge/workflows-${WORKFLOW_COUNT}-1e3a8a?style=for-the-badge)
![cadence](https://img.shields.io/badge/cadence-daily%208am%20UTC-064e3b?style=for-the-badge)
![refreshed](https://img.shields.io/badge/refreshed-${NOW_BADGE}-555?style=for-the-badge)

[Workflow source](.github/workflows/vitals.yml) ·
[Generator](.github/vitals/generate.sh) ·
[Deep dive](.github/docs/VITALS_DEEP_DIVE.md) ·
[Architecture](.github/docs/WORKFLOW_ARCHITECTURE.md) ·
[All workflows](.github/docs/WORKFLOWS_INDEX.md)

</div>

> [!IMPORTANT]
> Do not edit this file manually. Changes are overwritten on the next vitals run. See [.github/docs/VITALS_DEEP_DIVE.md](.github/docs/VITALS_DEEP_DIVE.md) for the full design.

> [!NOTE]
> Last refreshed at \`${NOW}\` by [.github/workflows/vitals.yml](.github/workflows/vitals.yml).

---

## At a glance

\`\`\`mermaid
flowchart LR
    classDef trig fill:#0b3954,color:#fff,stroke:#000
    classDef agent fill:#1e3a8a,color:#fff,stroke:#000
    classDef rel fill:#581c87,color:#fff,stroke:#000
    classDef hyg fill:#064e3b,color:#fff,stroke:#000
    classDef ext fill:#374151,color:#fff,stroke:#000

    T["Events<br/>cron, dispatch, PR, release,<br/>issue_comment, workflow_run, push"]:::trig
    A["Agent layer<br/>7 workflows<br/>(LLM-driven)"]:::agent
    R["Release pipeline<br/>6 workflows<br/>(dev to npm + S3)"]:::rel
    H["CI hygiene<br/>5 workflows<br/>(tests, caches, rebases)"]:::hyg
    X["External services<br/>Anthropic, GitHub, npm,<br/>AWS, Microsoft Graph"]:::ext

    T --> A
    T --> R
    T --> H
    A --> X
    R --> X
    H --> X
\`\`\`

---

## Workflow status

<details open>
<summary><strong>All workflows on the development branch</strong> (click to collapse)</summary>

| Workflow | Status |
|----------|--------|
EOF

# Status badges via shields.io
for wf in .github/workflows/*.yml; do
  name=$(basename "$wf" .yml)
  printf '| [%s](.github/workflows/%s.yml) | ![](https://img.shields.io/github/actions/workflow/status/%s/%s.yml?branch=development&style=flat-square&label=%%20) |\n' \
    "$name" "$name" "$REPO" "$name" >> "$OUTPUT"
done

# Agent activity section
cat >> "$OUTPUT" <<EOF

</details>

---

## Agent activity (last 7 days)

<details open>
<summary><strong>Run counts and last status per agent</strong></summary>

| Agent | Runs | Most recent status |
|-------|------|--------------------|
EOF

# Walk the log directories. Personas have nested subdirectories, so we handle them separately.
for dir in scripts/agents/logs/*/; do
  agent=$(basename "$dir")

  if [ "$agent" = "personas" ]; then
    for p in "$dir"*/; do
      pname=$(basename "$p")
      count=$(find "$p" -name '*.md' -newermt "$SEVEN_DAYS_AGO" 2>/dev/null | wc -l | tr -d ' ')
      latest=$(ls -t "$p"*.md 2>/dev/null | head -1)
      if [ -n "$latest" ]; then
        status=$(grep -m1 '^\- \*\*Status\*\*:' "$latest" 2>/dev/null | sed 's/.*Status\*\*: //' || echo "unknown")
      else
        status="no runs"
      fi
      printf '| personas/%s | %s | %s |\n' "$(md_escape "$pname")" "$count" "$(md_escape "$status")" >> "$OUTPUT"
    done
    continue
  fi

  count=$(find "$dir" -name '*.md' -newermt "$SEVEN_DAYS_AGO" 2>/dev/null | wc -l | tr -d ' ')
  latest=$(ls -t "$dir"*.md 2>/dev/null | head -1)
  if [ -n "$latest" ]; then
    status=$(grep -m1 '^\- \*\*Status\*\*:' "$latest" 2>/dev/null | sed 's/.*Status\*\*: //' || echo "unknown")
  else
    status="no runs"
  fi
  printf '| %s | %s | %s |\n' "$(md_escape "$agent")" "$count" "$(md_escape "$status")" >> "$OUTPUT"
done

# Health checks section
cat >> "$OUTPUT" <<EOF

</details>

---

## Health checks

EOF

if [ "$STALE_PR_COUNT" -gt 0 ]; then
  echo "- [WARN] ${STALE_PR_COUNT} bot PR(s) awaiting review for over 72 hours:" >> "$OUTPUT"
  # Walk the array one PR at a time so each title can be md-escaped.
  echo "$STALE_PRS" | jq -c '.[]' | while IFS= read -r pr; do
    pr_num=$(echo "$pr" | jq -r '.number')
    pr_title=$(echo "$pr" | jq -r '.title')
    pr_url=$(echo "$pr" | jq -r '.url')
    pr_title_esc=$(md_escape "$pr_title")
    echo "    - [#${pr_num} ${pr_title_esc}](${pr_url})"
  done >> "$OUTPUT"
else
  echo "- [OK] No bot PRs stale beyond 72 hours" >> "$OUTPUT"
fi

if [ "$OPEN_BOT_PRS" -gt 20 ]; then
  echo "- [WARN] Open bot PRs: ${OPEN_BOT_PRS} (cap 20). Cron-triggered agents are paused by the backlog gate." >> "$OUTPUT"
else
  echo "- [OK] Open bot PRs: ${OPEN_BOT_PRS} / 20 cap" >> "$OUTPUT"
fi

if [ "$OPEN_ISSUES" -gt 40 ]; then
  echo "- [WARN] Open issues: ${OPEN_ISSUES} (cap 40). Cron-triggered agents are paused by the backlog gate." >> "$OUTPUT"
else
  echo "- [OK] Open issues: ${OPEN_ISSUES} / 40 cap" >> "$OUTPUT"
fi

if [ "$NEEDS_DISCUSSION" -gt 0 ]; then
  echo "- [INFO] ${NEEDS_DISCUSSION} issue(s) labeled \`needs-discussion\` waiting on a human call" >> "$OUTPUT"
fi

if [ "$BREAKING_ISSUES" -gt 0 ]; then
  echo "- [INFO] ${BREAKING_ISSUES} issue(s) labeled \`breaking\` parked for the next major" >> "$OUTPUT"
fi

# Last release section
RELEASE_TAG_ESC=$(md_escape "$RELEASE_TAG")
RELEASE_DATE_ESC=$(md_escape "$RELEASE_DATE")

cat >> "$OUTPUT" <<EOF

---

## Release status

| Field | Value |
|-------|-------|
| **Latest published** | \`${RELEASE_TAG_ESC}\` on ${RELEASE_DATE_ESC} |
EOF

if [ -n "$RELEASE_URL" ] && [ "$RELEASE_URL" != "null" ]; then
  echo "- **Link**: ${RELEASE_URL}" >> "$OUTPUT"
fi

if [ "$DEV_DRAFT" != "null" ] && [ -n "$DEV_DRAFT" ]; then
  DRAFT_NUM=$(echo "$DEV_DRAFT" | jq -r '.number')
  DRAFT_TITLE=$(echo "$DEV_DRAFT" | jq -r '.title')
  DRAFT_URL=$(echo "$DEV_DRAFT" | jq -r '.url')
  DRAFT_DRAFT_STATE=$(echo "$DEV_DRAFT" | jq -r '.isDraft')
  if [ "$DRAFT_DRAFT_STATE" = "true" ]; then
    DRAFT_LABEL="draft"
  else
    DRAFT_LABEL="ready for review"
  fi
  DRAFT_TITLE_ESC=$(md_escape "$DRAFT_TITLE")
  printf '| **Next release queue** | PR [#%s](%s) "%s" (%s) |\n' \
    "$DRAFT_NUM" "$DRAFT_URL" "$DRAFT_TITLE_ESC" "$DRAFT_LABEL" >> "$OUTPUT"
else
  echo "| **Next release queue** | no open development to main PR |" >> "$OUTPUT"
fi

# Quick links section
cat >> "$OUTPUT" <<EOF

---

<div align="center">

### Quick links

[Workflow index](.github/docs/WORKFLOWS_INDEX.md) ·
[Architecture](.github/docs/WORKFLOW_ARCHITECTURE.md) ·
[Agent runtime](.github/docs/AGENT_RUN_DEEP_DIVE.md) ·
[Docs-sync](.github/docs/DOCS_SYNC_DEEP_DIVE.md) ·
[Vitals](.github/docs/VITALS_DEEP_DIVE.md)

</div>
EOF
